# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 22:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCIDevice',
            fields=[
                ('device_id', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_updatable', models.BooleanField(default=True)),
                ('chipset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.PCIDevice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCIVendor',
            fields=[
                ('vendor_id', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_updatable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USBDevice',
            fields=[
                ('device_id', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_updatable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USBVendor',
            fields=[
                ('vendor_id', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_updatable', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
