# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCIDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=200)),
                ('is_updatable', models.BooleanField(default=True)),
                ('chipset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.PCIDevice')),
            ],
        ),
        migrations.CreateModel(
            name='PCIVendor',
            fields=[
                ('vendor_id', models.CharField(db_index=True, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_updatable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='pcidevice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.PCIVendor'),
        ),
        migrations.AlterUniqueTogether(
            name='pcidevice',
            unique_together=set([('vendor', 'chipset', 'device_id')]),
        ),
    ]
